# Рядок version: '3.8' ми прибрали, як і обговорювали
services:
  web:
    # Збирати образ з Dockerfile, що лежить у цій же папці
    build: .
    # Прокидаємо порт 8080 на твоєму комп'ютері на порт 80 всередині контейнера
    ports:
      - "8080:80"
    # Монтуємо локальну папку 'dist', щоб бачити зміни миттєво
    volumes:
      - ./dist:/var/www/html